apiVersion: apps/v1
kind: Deployment
metadata:
  name: pl-app
  labels:
    app: pl-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pl-app
  template:
    metadata:
      labels:
        app: pl-app
    spec:
      containers:
        - name: pl-app
          image: jpumpkin93/pl-app:latest
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
      terminationGracePeriodSeconds: 0
---

apiVersion: v1
kind: Service
metadata:
  name: pl-app
  labels:
    app: pl-app
spec:
  type: NodePort
  ports:
      - protocol: TCP
        port: 3000
        targetPort: 8080
  selector:
    app: pl-app