apiVersion: apps/v1
kind: Deployment
metadata:
  name: pl-app
  labels:
    app: pl-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: pl-app
  template:
    metadata:
      labels:
        app: pl-app
    spec:
      containers:
        - name: pl-app
          image: jpumpkin93/pl-app:latest
          ports:
            - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: pl-app
  labels:
    app: pl-app
spec:
  type: LoadBalancer
  ports:
    - name: 3000-tcp
      port: 3000
      protocol: TCP
      targetPort: 8080
  selector:
    app: pl-app
status:
  loadBalancer: {}